/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthcheck': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetHealthcheck'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head: operations['HeadHealthcheck'];
    patch?: never;
    trace?: never;
  };
  '/tf-ops/api/v1/hcp/integrations/{integrationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getHcpIntegration'];
    put?: never;
    post?: never;
    delete: operations['deleteHcpIntegration'];
    options?: never;
    head: operations['getHcpIntegration__HEAD'];
    patch?: never;
    trace?: never;
  };
  '/tf-ops/api/v1/hcp/integrations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAllHcpIntegrations'];
    put?: never;
    post: operations['createHcpIntegration'];
    delete?: never;
    options?: never;
    head: operations['getAllHcpIntegrations__HEAD'];
    patch?: never;
    trace?: never;
  };
  '/tf-ops/api/v1/hcp/webhooks/terraform-run-task/{integrationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationId'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tf-ops/api/v1/hcp/webhooks/notifications/{integrationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['PostTfOpsApiV1HcpWebhooksNotificationsIntegrationId'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tf-ops/api/v1/hcp/drift/terraform-plan/{driftNotificationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationId'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head: operations['HeadTfOpsApiV1HcpDriftTerraformPlanDriftNotificationId'];
    patch?: never;
    trace?: never;
  };
  '/reporting/orl-external': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['createOrlReportEvent'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reporting/orl-fix-applied': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['createOrlFixAppliedEvent'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    GetHealthcheckPositiveResponse: {
      /** @constant */
      status: 'success';
      data: {
        status: string;
        timestamp: string;
      };
    };
    GetHealthcheckNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    GetTfOpsApiV1HcpIntegrationsIntegrationIdParameterIntegrationId: string;
    GetTfOpsApiV1HcpIntegrationsIntegrationIdParameterXOrganizationId: string;
    GetTfOpsApiV1HcpIntegrationsIntegrationIdPositiveResponse: {
      /** @constant */
      status: 'success';
      data: {
        deletedAt?: unknown;
        /** Format: uuid */
        integrationId: string;
        /** Format: uuid */
        organizationId: string;
        /** Format: email */
        createdBy: string;
        name: string;
        HMACKey: string;
        createdAt: unknown;
        /** Format: uri */
        webhookUrl: string;
        /** @enum {string} */
        type: 'RUN_TASK' | 'NOTIFICATION';
      };
    };
    GetTfOpsApiV1HcpIntegrationsIntegrationIdNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    HeadTfOpsApiV1HcpIntegrationsIntegrationIdParameterIntegrationId: string;
    HeadTfOpsApiV1HcpIntegrationsIntegrationIdParameterXOrganizationId: string;
    DeleteTfOpsApiV1HcpIntegrationsIntegrationIdParameterIntegrationId: string;
    DeleteTfOpsApiV1HcpIntegrationsIntegrationIdParameterXOrganizationId: string;
    DeleteTfOpsApiV1HcpIntegrationsIntegrationIdPositiveResponse: {
      /** @constant */
      status: 'success';
      data: {
        integrationId: string;
      };
    };
    DeleteTfOpsApiV1HcpIntegrationsIntegrationIdNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    PostTfOpsApiV1HcpIntegrationsParameterXOrganizationId: string;
    PostTfOpsApiV1HcpIntegrationsPositiveResponse: {
      /** @constant */
      status: 'success';
      data: {
        deletedAt?: unknown;
        /** Format: uuid */
        integrationId: string;
        /** Format: uuid */
        organizationId: string;
        /** Format: email */
        createdBy: string;
        name: string;
        HMACKey: string;
        createdAt: unknown;
        /** Format: uri */
        webhookUrl: string;
        /** @enum {string} */
        type: 'RUN_TASK' | 'NOTIFICATION';
      };
    };
    PostTfOpsApiV1HcpIntegrationsNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    PostTfOpsApiV1HcpIntegrationsRequestBody: {
      /** Format: email */
      createdBy: string;
      name?: string;
      /** @enum {string} */
      type: 'RUN_TASK' | 'NOTIFICATION';
      pat?: string;
    };
    GetTfOpsApiV1HcpIntegrationsParameterXOrganizationId: string;
    GetTfOpsApiV1HcpIntegrationsPositiveResponse: {
      /** @constant */
      status: 'success';
      data: {
        integrations: {
          deletedAt?: unknown;
          /** Format: uuid */
          integrationId: string;
          /** Format: uuid */
          organizationId: string;
          /** Format: email */
          createdBy: string;
          name: string;
          HMACKey: string;
          createdAt: unknown;
          /** Format: uri */
          webhookUrl: string;
          /** @enum {string} */
          type: 'RUN_TASK' | 'NOTIFICATION';
        }[];
      };
    };
    GetTfOpsApiV1HcpIntegrationsNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    HeadTfOpsApiV1HcpIntegrationsParameterXOrganizationId: string;
    /** Format: uuid */
    PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationIdParameterIntegrationId: string;
    PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationIdPositiveResponse: {
      /** @constant */
      status: 'success';
      data: Record<string, never>;
    };
    PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationIdNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationIdRequestBody: {
      payload_version: number;
      stage: string;
      access_token: string;
      capabilities: {
        outcomes: boolean;
      };
      /** Format: uri */
      configuration_version_download_url: string;
      configuration_version_id: string;
      is_speculative: boolean;
      organization_name: string;
      /** Format: uri */
      plan_json_api_url?: string;
      /** Format: uri */
      run_app_url: string;
      run_created_at: string;
      run_created_by: string;
      run_id: string;
      run_message: string;
      /** Format: uri */
      task_result_callback_url: string;
      /** @enum {string} */
      task_result_enforcement_level: 'mandatory' | 'advisory' | 'test';
      task_result_id: string;
      vcs_branch: string | null;
      /** Format: uri */
      vcs_commit_url: string | null;
      /** Format: uri */
      vcs_pull_request_url: string | null;
      /** Format: uri */
      vcs_repo_url: string | null;
      /** Format: uri */
      workspace_app_url: string;
      workspace_id: string;
      workspace_name: string;
      workspace_working_directory: string;
    };
    /** Format: uuid */
    PostTfOpsApiV1HcpWebhooksNotificationsIntegrationIdParameterIntegrationId: string;
    PostTfOpsApiV1HcpWebhooksNotificationsIntegrationIdPositiveResponse: {
      /** @constant */
      status: 'success';
      data: Record<string, never>;
    };
    PostTfOpsApiV1HcpWebhooksNotificationsIntegrationIdNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    PostTfOpsApiV1HcpWebhooksNotificationsIntegrationIdRequestBody: {
      payload_version: 'PostTfOpsApiV1HcpWebhooksNotificationsIntegrationIdRequestBody';
    } & (Record<string, never> &
      Record<string, never> &
      Omit<
        | {
            /** @constant */
            payload_version: 1;
            notification_configuration_id: string;
            /** Format: uri */
            run_url: string | null;
            run_id: string | null;
            run_message: string | null;
            /** Format: date-time */
            run_created_at: string | null;
            run_created_by: string | null;
            workspace_id: string | null;
            workspace_name: string | null;
            organization_name: string | null;
            notifications: {
              message: string;
              /** @enum {string} */
              trigger:
                | 'run:created'
                | 'run:planning'
                | 'run:needs_attention'
                | 'run:applying'
                | 'run:completed'
                | 'run:errored'
                | 'assessment:drifted'
                | 'assessment:check_failure'
                | 'assessment:failed'
                | 'workspace:auto_destroy_reminder'
                | 'workspace:auto_destroy_run_results'
                | 'verification';
              run_status: string | null;
              /** Format: date-time */
              run_updated_at: string | null;
              run_updated_by: string | null;
            }[];
          }
        | {
            /** @constant */
            payload_version: '2';
            notification_configuration_id: string;
            /** Format: uri */
            notification_configuration_url: string;
            /** @enum {string} */
            trigger_scope: 'assessment' | 'workspace';
            /** @enum {string} */
            trigger:
              | 'run:created'
              | 'run:planning'
              | 'run:needs_attention'
              | 'run:applying'
              | 'run:completed'
              | 'run:errored'
              | 'assessment:drifted'
              | 'assessment:check_failure'
              | 'assessment:failed'
              | 'workspace:auto_destroy_reminder'
              | 'workspace:auto_destroy_run_results'
              | 'verification';
            message: string;
            details: {
              new_assessment_result?: {
                id: string;
                /** Format: uri */
                url: string;
                succeeded: boolean;
                drifted: boolean;
                all_checks_succeeded: boolean;
                resources_drifted: number;
                resources_undrifted: number;
                checks_passed: number;
                checks_failed: number;
                checks_errored: number;
                checks_unknown: number;
                /** Format: date-time */
                created_at: string;
              };
              prior_assessment_result?: {
                id: string;
                /** Format: uri */
                url: string;
                succeeded: boolean;
                drifted: boolean;
                all_checks_succeeded: boolean;
                resources_drifted: number;
                resources_undrifted: number;
                checks_passed: number;
                checks_failed: number;
                checks_errored: number;
                checks_unknown: number;
                /** Format: date-time */
                created_at: string;
              };
              workspace_id?: string;
              workspace_name: string;
              organization_name: string;
              /** Format: date-time */
              auto_destroy_at?: string | null;
              /** Format: date-time */
              run_created_at?: string | null;
              run_status?: string | null;
              run_external_id?: string | null;
              run_create_error_message?: string | null;
              /** @enum {string} */
              trigger_type?: 'reminder' | 'results';
            };
          },
        'payload_version'
      >);
    GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdParameterDriftNotificationId: string;
    GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdParameterXOrganizationId: string;
    GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdPositiveResponse: {
      /** @constant */
      status: 'success';
      data: {
        rawTerraformPlan: string;
      };
    };
    GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    HeadTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdParameterDriftNotificationId: string;
    HeadTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdParameterXOrganizationId: string;
    PostReportingOrlExternalPositiveResponse: {
      /** @constant */
      status: 'success';
      data: {
        success: boolean;
        message: string;
        jobId?: string;
      };
    };
    PostReportingOrlExternalNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    PostReportingOrlExternalRequestBody: {
      /** @default 1 */
      version: number;
      /** @enum {string} */
      requestOrigin: 'GITHUB_ACTION' | 'IDE' | 'MCP' | 'CODE_AGENT';
      effect?: string;
      reports: {
        path?: string;
        branch?: string;
        orlReport?: {
          /** @constant */
          type: 'Report';
          /** @constant */
          version: 'v1';
          metadata: {
            name: string;
            description?: string;
            priority?: number;
            skip?: boolean;
            required_contexts?: string[];
            annotations?: {
              [key: string]: string;
            };
          };
          workspace: string;
          language: string;
          rules_applied: number;
          findings: number;
          fixes: number;
          changes: number;
          errors: unknown[];
          rules: {
            metadata: {
              name: string;
              description?: string;
              priority?: number;
              skip?: boolean;
              required_contexts?: string[];
              annotations?: {
                [key: string]: string;
              };
              classifications?: string[];
            };
            name: string;
            findings: number;
            fixes: number;
            changes: number;
            errors: unknown[];
            files: {
              path: string;
            }[];
          }[];
        } & {
          [key: string]: unknown;
        };
      }[];
      errors: {
        status: number;
        message: string;
      }[];
      durationInSeconds: number;
      scmContext?: {
        scmType: 'GITHUB' | 'GITLAB' | 'BITBUCKET' | 'AZDO';
        originalPullRequest?: {
          id: string;
          /** Format: uri */
          url: string;
          author: string;
        };
        resultingPullRequest?: {
          id: string;
          /** Format: uri */
          url: string;
          author: string;
        };
      };
    };
    PostReportingOrlFixAppliedPositiveResponse: {
      /** @constant */
      status: 'success';
      data: {
        success: boolean;
        message: string;
      };
    };
    PostReportingOrlFixAppliedNegativeResponse: {
      /** @constant */
      status: 'error';
      error: {
        message: string;
      };
    };
    PostReportingOrlFixAppliedRequestBody: {
      /** @default 1 */
      version: number;
      requestOrigin: string;
      events: ({
        /** @constant */
        type: 'orl_fix_applied';
        idempotencyKey: string;
        occurredAt: string;
        /** @enum {string} */
        fixKind: 'individual' | 'grouped';
        /** @default [] */
        ruleNames: string[];
        /** @default [] */
        ruleIdentifiers: string[];
        /** @default [] */
        filePaths: string[];
        repoPath?: string;
        branch?: string;
      } & {
        [key: string]: unknown;
      })[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetHealthcheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GET /healthcheck Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetHealthcheckPositiveResponse'];
        };
      };
      /** @description GET /healthcheck Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetHealthcheckNegativeResponse'];
        };
      };
    };
  };
  HeadHealthcheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description HEAD /healthcheck Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description HEAD /healthcheck Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getHcpIntegration: {
    parameters: {
      query?: never;
      header: {
        /** @description GET /tf-ops/api/v1/hcp/integrations/:integrationId Parameter */
        'x-organization-id': components['schemas']['GetTfOpsApiV1HcpIntegrationsIntegrationIdParameterXOrganizationId'];
      };
      path: {
        /** @description GET /tf-ops/api/v1/hcp/integrations/:integrationId Parameter */
        integrationId: components['schemas']['GetTfOpsApiV1HcpIntegrationsIntegrationIdParameterIntegrationId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GET /tf-ops/api/v1/hcp/integrations/:integrationId Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetTfOpsApiV1HcpIntegrationsIntegrationIdPositiveResponse'];
        };
      };
      /** @description GET /tf-ops/api/v1/hcp/integrations/:integrationId Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetTfOpsApiV1HcpIntegrationsIntegrationIdNegativeResponse'];
        };
      };
    };
  };
  deleteHcpIntegration: {
    parameters: {
      query?: never;
      header: {
        /** @description DELETE /tf-ops/api/v1/hcp/integrations/:integrationId Parameter */
        'x-organization-id': components['schemas']['DeleteTfOpsApiV1HcpIntegrationsIntegrationIdParameterXOrganizationId'];
      };
      path: {
        /** @description DELETE /tf-ops/api/v1/hcp/integrations/:integrationId Parameter */
        integrationId: components['schemas']['DeleteTfOpsApiV1HcpIntegrationsIntegrationIdParameterIntegrationId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description DELETE /tf-ops/api/v1/hcp/integrations/:integrationId Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteTfOpsApiV1HcpIntegrationsIntegrationIdPositiveResponse'];
        };
      };
      /** @description DELETE /tf-ops/api/v1/hcp/integrations/:integrationId Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteTfOpsApiV1HcpIntegrationsIntegrationIdNegativeResponse'];
        };
      };
    };
  };
  getHcpIntegration__HEAD: {
    parameters: {
      query?: never;
      header: {
        /** @description HEAD /tf-ops/api/v1/hcp/integrations/:integrationId Parameter */
        'x-organization-id': components['schemas']['HeadTfOpsApiV1HcpIntegrationsIntegrationIdParameterXOrganizationId'];
      };
      path: {
        /** @description HEAD /tf-ops/api/v1/hcp/integrations/:integrationId Parameter */
        integrationId: components['schemas']['HeadTfOpsApiV1HcpIntegrationsIntegrationIdParameterIntegrationId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description HEAD /tf-ops/api/v1/hcp/integrations/:integrationId Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description HEAD /tf-ops/api/v1/hcp/integrations/:integrationId Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAllHcpIntegrations: {
    parameters: {
      query?: never;
      header: {
        /** @description GET /tf-ops/api/v1/hcp/integrations Parameter */
        'x-organization-id': components['schemas']['GetTfOpsApiV1HcpIntegrationsParameterXOrganizationId'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GET /tf-ops/api/v1/hcp/integrations Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetTfOpsApiV1HcpIntegrationsPositiveResponse'];
        };
      };
      /** @description GET /tf-ops/api/v1/hcp/integrations Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetTfOpsApiV1HcpIntegrationsNegativeResponse'];
        };
      };
    };
  };
  createHcpIntegration: {
    parameters: {
      query?: never;
      header: {
        /** @description POST /tf-ops/api/v1/hcp/integrations Parameter */
        'x-organization-id': components['schemas']['PostTfOpsApiV1HcpIntegrationsParameterXOrganizationId'];
      };
      path?: never;
      cookie?: never;
    };
    /** @description POST /tf-ops/api/v1/hcp/integrations Request body */
    requestBody: {
      content: {
        'application/json': components['schemas']['PostTfOpsApiV1HcpIntegrationsRequestBody'];
      };
    };
    responses: {
      /** @description POST /tf-ops/api/v1/hcp/integrations Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostTfOpsApiV1HcpIntegrationsPositiveResponse'];
        };
      };
      /** @description POST /tf-ops/api/v1/hcp/integrations Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostTfOpsApiV1HcpIntegrationsNegativeResponse'];
        };
      };
    };
  };
  getAllHcpIntegrations__HEAD: {
    parameters: {
      query?: never;
      header: {
        /** @description HEAD /tf-ops/api/v1/hcp/integrations Parameter */
        'x-organization-id': components['schemas']['HeadTfOpsApiV1HcpIntegrationsParameterXOrganizationId'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description HEAD /tf-ops/api/v1/hcp/integrations Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description HEAD /tf-ops/api/v1/hcp/integrations Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description POST /tf-ops/api/v1/hcp/webhooks/terraform-run-task/:integrationId Parameter */
        integrationId: components['schemas']['PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationIdParameterIntegrationId'];
      };
      cookie?: never;
    };
    /** @description POST /tf-ops/api/v1/hcp/webhooks/terraform-run-task/:integrationId Request body */
    requestBody: {
      content: {
        'application/json': components['schemas']['PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationIdRequestBody'];
      };
    };
    responses: {
      /** @description POST /tf-ops/api/v1/hcp/webhooks/terraform-run-task/:integrationId Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationIdPositiveResponse'];
        };
      };
      /** @description POST /tf-ops/api/v1/hcp/webhooks/terraform-run-task/:integrationId Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostTfOpsApiV1HcpWebhooksTerraformRunTaskIntegrationIdNegativeResponse'];
        };
      };
    };
  };
  PostTfOpsApiV1HcpWebhooksNotificationsIntegrationId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description POST /tf-ops/api/v1/hcp/webhooks/notifications/:integrationId Parameter */
        integrationId: components['schemas']['PostTfOpsApiV1HcpWebhooksNotificationsIntegrationIdParameterIntegrationId'];
      };
      cookie?: never;
    };
    /** @description POST /tf-ops/api/v1/hcp/webhooks/notifications/:integrationId Request body */
    requestBody: {
      content: {
        'application/json': components['schemas']['PostTfOpsApiV1HcpWebhooksNotificationsIntegrationIdRequestBody'];
      };
    };
    responses: {
      /** @description POST /tf-ops/api/v1/hcp/webhooks/notifications/:integrationId Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostTfOpsApiV1HcpWebhooksNotificationsIntegrationIdPositiveResponse'];
        };
      };
      /** @description POST /tf-ops/api/v1/hcp/webhooks/notifications/:integrationId Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostTfOpsApiV1HcpWebhooksNotificationsIntegrationIdNegativeResponse'];
        };
      };
    };
  };
  GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationId: {
    parameters: {
      query?: never;
      header: {
        /** @description GET /tf-ops/api/v1/hcp/drift/terraform-plan/:driftNotificationId Parameter */
        'x-organization-id': components['schemas']['GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdParameterXOrganizationId'];
      };
      path: {
        /** @description GET /tf-ops/api/v1/hcp/drift/terraform-plan/:driftNotificationId Parameter */
        driftNotificationId: components['schemas']['GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdParameterDriftNotificationId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GET /tf-ops/api/v1/hcp/drift/terraform-plan/:driftNotificationId Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdPositiveResponse'];
        };
      };
      /** @description GET /tf-ops/api/v1/hcp/drift/terraform-plan/:driftNotificationId Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdNegativeResponse'];
        };
      };
    };
  };
  HeadTfOpsApiV1HcpDriftTerraformPlanDriftNotificationId: {
    parameters: {
      query?: never;
      header: {
        /** @description HEAD /tf-ops/api/v1/hcp/drift/terraform-plan/:driftNotificationId Parameter */
        'x-organization-id': components['schemas']['HeadTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdParameterXOrganizationId'];
      };
      path: {
        /** @description HEAD /tf-ops/api/v1/hcp/drift/terraform-plan/:driftNotificationId Parameter */
        driftNotificationId: components['schemas']['HeadTfOpsApiV1HcpDriftTerraformPlanDriftNotificationIdParameterDriftNotificationId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description HEAD /tf-ops/api/v1/hcp/drift/terraform-plan/:driftNotificationId Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description HEAD /tf-ops/api/v1/hcp/drift/terraform-plan/:driftNotificationId Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createOrlReportEvent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description POST /reporting/orl-external Request body */
    requestBody: {
      content: {
        'application/json': components['schemas']['PostReportingOrlExternalRequestBody'];
      };
    };
    responses: {
      /** @description POST /reporting/orl-external Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostReportingOrlExternalPositiveResponse'];
        };
      };
      /** @description POST /reporting/orl-external Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostReportingOrlExternalNegativeResponse'];
        };
      };
    };
  };
  createOrlFixAppliedEvent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description POST /reporting/orl-fix-applied Request body */
    requestBody: {
      content: {
        'application/json': components['schemas']['PostReportingOrlFixAppliedRequestBody'];
      };
    };
    responses: {
      /** @description POST /reporting/orl-fix-applied Positive response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostReportingOrlFixAppliedPositiveResponse'];
        };
      };
      /** @description POST /reporting/orl-fix-applied Negative response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostReportingOrlFixAppliedNegativeResponse'];
        };
      };
    };
  };
}
