/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Ruleset {
  /**
   * 'type' defines the type of object
   */
  type: "Rule" | "Test" | "Ruleset" | "Context" | "Variables" | "Report";
  /**
   * 'version' defines the parsing of the spec
   */
  version: "v1";
  /**
   * 'metadata' is the metadata for the object
   */
  metadata: {
    /**
     * Name uniquely identifies the name among all rules
     */
    name: string;
    /**
     * 'display_name' is a human-readable display name for the rule
     */
    display_name?: string;
    /**
     * 'skip' allows the creation of rules that are skipped.  Deprecated, used 'skip_expression' instead.
     */
    skip?: boolean;
    /**
     * 'skip_expression' is a template expression that is evaluated to determine if the item should be skipped.
     */
    skip_expression?: string;
    /**
     * 'skip_reason' is a human-readable reason for why the item is skipped.  This will be logged at INFO level in the report, if the item is skipped.
     */
    skip_reason?: string;
    /**
     * priority defines the order in which the rule is evaluated.  If not provided then it sorts last
     */
    priority?: number;
    /**
     * 'description' is a human-readable description of the rule
     */
    description?: string;
    /**
     * 'required_contexts' is a list of contexts that are required for the rule to run.  Deprecated, used 'skip_expression' instead.
     */
    required_contexts?: string[];
    /**
     * 'annotations' are a map of key-value pairs that are used to store additional information about the rule
     */
    annotations?: {
      [k: string]: string;
    };
    /**
     * 'classifications' are the classifications of the rule as an array of strings.
     */
    classifications?: string[];
  };
  spec: {
    /**
     * 'template' is the template for a ruleset.  It becomes the base for all rules.
     */
    template?: {
      /**
       * 'language' defines the what language this rule is valid for.
       */
      language?: string;
      /**
       * 'audit_language' is the language to use for the audit query.  Language is used if not defined.
       */
      audit_language?: "ast";
      /**
       * 'variables' is a list of variables that are needed for this rule to be evaluated.  Deprecated, use 'metadata.skip_expression' instead.
       */
      variables?: string[];
      /**
       * 'collect' is a list of AST nodes to collect from the workspace before evaluating the rule.  They can be later used to build a remediation.
       */
      collect?: {
        name: string;
        audit: string;
      }[];
      /**
       * 'audit' is the audit query for this rule.  It is a string that is parsed based on 'audit_language'.  For 'audit_language' of 'ast' the audit query is an S-expression.
       */
      audit?: string;
      /**
       * 'skip' is a boolean that indicates if the rule should be skipped.  This overrides metadata.skip.  This is deprecated, use 'skip_expression' instead.
       */
      skip?: boolean;
      /**
       * 'skip_expression' is a template expression that is evaluated to determine if the rule should be skipped.  This overrides metadata.skip_expression.
       */
      skip_expression?: string;
      /**
       * 'skip_reason' is a human-readable reason for why the rule is skipped.  This will be logged at INFO level in the report, if the rule is skipped.
       */
      skip_reason?: string;
      /**
       * 'skip_finding' is a template expression to determine if the finding should be skipped.  If true the finding is not counted, nor are any remediations applied.
       */
      skip_finding?: string;
      /**
       * 'skip_finding_reason' is a human-readable reason for why the finding is skipped.  This will be logged at INFO level in the report, if the finding is skipped.
       */
      skip_finding_reason?: string;
      /**
       * 'remediation' is a list of commands to run to remediate the issue.  Each command is run in order on all audit findings.
       */
      remediation?: {
        /**
         * 'command' is the command to execute.  The command is executed on the captured node in 'path'.
         */
        command: string;
        /**
         * 'path' is the path to the captured node to execute the command against. This is the anchor point for the command.
         */
        path?: string;
        /**
         * 'skip' is a template expression that is evaluated to determine if the remediation should be skipped.  If true then the remediation is skipped.
         */
        skip?: string;
        /**
         * 'invert_skip' adds 'not' in front of 'skip' to invert the skip condition.  This can make the skip condition more readable.
         */
        invert_skip?: boolean;
        /**
         * 'skip_reason' is a human-readable reason for why the remediation is skipped.  This will be logged at INFO level in the report, if the remediation is skipped.
         */
        skip_reason?: string;
        /**
         * 'value' is the value to use with the command.  It supports multiple templates.
         */
        value?: string;
        /**
         * Flags are any flags that can modify the behavior of the command. They are all `key: value` string pairs.
         */
        flags?: {
          [k: string]: string;
        };
      }[];
    };
    /**
     * 'foreach' is a template expression that must evaluate to an array.  Each rule in the ruleset will be executed once for each item in the array.  The current item is available in the templator context as "item".
     */
    foreach?: string;
    /**
     * 'rules' is a list of rules.
     */
    rules: {
      /**
       * 'name' is the name of the rule.  This becomes the annotation "ruleset-case-name".
       */
      name?: string;
      /**
       * 'skip' is a boolean that indicates if the rule should be skipped.  This overrides metadata.skip.  This is deprecated, use 'skip_expression' instead.
       */
      skip?: boolean;
      /**
       * 'skip_expression' is a template expression that is evaluated to determine if the rule should be skipped.  This overrides metadata.skip_expression.
       */
      skip_expression?: string;
      /**
       * 'skip_reason' is a human-readable reason for why the rule is skipped.  This will be logged at INFO level in the report, if the rule is skipped. This overrides metadata.skip_reason.
       */
      skip_reason?: string;
      /**
       * 'language' defines the what language this rule is valid for.
       */
      language?: string;
      /**
       * 'audit_language' is the language to use for the audit query.  Language is used if not defined.
       */
      audit_language?: "ast";
      /**
       * 'variables' is a list of variables that are needed for this rule to be evaluated.  Deprecated, use 'metadata.skip_expression' instead.
       */
      variables?: string[];
      /**
       * 'audit' is the audit query for this rule.  It is a string that is parsed based on 'audit_language'.  For 'audit_language' of 'ast' the audit query is an S-expression.
       */
      audit?: string;
      /**
       * 'skip_finding' is a template expression to determine if the finding should be skipped.  If true the finding is not counted, nor are any remediations applied.
       */
      skip_finding?: string;
      /**
       * 'skip_finding_reason' is a human-readable reason for why the finding is skipped.  This will be logged at INFO level in the report, if the finding is skipped.
       */
      skip_finding_reason?: string;
      /**
       * 'remediation' is a list of commands to run to remediate the issue.  Each command is run in order on all audit findings.
       */
      remediation?: {
        /**
         * 'command' is the command to execute.  The command is executed on the captured node in 'path'.
         */
        command: string;
        /**
         * 'path' is the path to the captured node to execute the command against. This is the anchor point for the command.
         */
        path?: string;
        /**
         * 'skip' is a template expression that is evaluated to determine if the remediation should be skipped.  If true then the remediation is skipped.
         */
        skip?: string;
        /**
         * 'invert_skip' adds 'not' in front of 'skip' to invert the skip condition.  This can make the skip condition more readable.
         */
        invert_skip?: boolean;
        /**
         * 'skip_reason' is a human-readable reason for why the remediation is skipped.  This will be logged at INFO level in the report, if the remediation is skipped.
         */
        skip_reason?: string;
        /**
         * 'value' is the value to use with the command.  It supports multiple templates.
         */
        value?: string;
        /**
         * Flags are any flags that can modify the behavior of the command. They are all `key: value` string pairs.
         */
        flags?: {
          [k: string]: string;
        };
      }[];
      /**
       * 'collect' is a list of AST nodes to collect from the workspace before evaluating the rule.  They can be later used to build a remediation.
       */
      collect?: {
        name: string;
        audit: string;
      }[];
      /**
       * 'foreach' is a template expression that MUST evaluate to an array.  Each rule in the ruleset will be executed once for each item in the array.  The current item is available in the templator context as "item".
       */
      foreach?: string;
    }[];
  };
}
