/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Report is the final result of the remediation that is filled out during the remediation.
 */
export interface Report {
  /**
   * 'type' defines the type of object
   */
  type: 'Rule' | 'Test' | 'Ruleset' | 'Context' | 'Variables' | 'Report';
  /**
   * 'version' defines the parsing of the spec
   */
  version: 'v1';
  /**
   * 'metadata' is the metadata for the object
   */
  metadata: {
    /**
     * Name uniquely identifies the name among all rules
     */
    name: string;
    /**
     * 'display_name' is a human-readable display name for the rule
     */
    display_name?: string;
    /**
     * 'skip' allows the creation of rules that are skipped.  Deprecated, used 'skip_expression' instead.
     */
    skip?: boolean;
    /**
     * 'skip_expression' is a template expression that is evaluated to determine if the item should be skipped.
     */
    skip_expression?: string;
    /**
     * 'skip_reason' is a human-readable reason for why the item is skipped.  This will be logged at INFO level in the report, if the item is skipped.
     */
    skip_reason?: string;
    /**
     * priority defines the order in which the rule is evaluated.  If not provided then it sorts last
     */
    priority?: number;
    /**
     * 'description' is a human-readable description of the rule
     */
    description?: string;
    /**
     * 'required_contexts' is a list of contexts that are required for the rule to run.  Deprecated, used 'skip_expression' instead.
     */
    required_contexts?: string[];
    /**
     * 'annotations' are a map of key-value pairs that are used to store additional information about the rule
     */
    annotations?: {
      [k: string]: string;
    };
    /**
     * 'classifications' are the classifications of the rule as an array of strings.
     */
    classifications?: string[];
  };
  /**
   * 'spec' is the specification for the report
   */
  spec: {
    /**
     * 'workspace' is the path to the workspace that was remediated
     */
    workspace: string;
    /**
     * 'language' is the language of the workspace that was remediated
     */
    language: string;
    /**
     * 'rules_applied' is the number of rules that were applied
     */
    rules_applied: number;
    /**
     * 'rules_skipped' is the number of rules that were skipped
     */
    rules_skipped: number;
    /**
     * 'findings' is the number of findings found during the audit
     */
    findings: number;
    /**
     * 'fixes' is the number of fixes that were applied
     */
    fixes: number;
    /**
     * 'changes' is the total number of changes applied.  In many cases a remediation requires more then one change
     */
    changes: number;
    /**
     * 'files_changed' is a map of file paths to a struct indicating that the file was changed
     */
    files_changed: {
      [k: string]: {};
    };
    /**
     * 'errors' is a collection of all the errors that were encountered
     */
    errors: unknown[];
    /**
     * logs is a list of all log messages.
     */
    logs?: {
      time?: string;
      level?: 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR' | 'FATAL';
      message: string;
      source?: string;
      data?: {
        [k: string]: unknown;
      };
    }[];
    /**
     * logs_count is the number of log messages.
     */
    logs_count?: number;
    /**
     * 'error_count' is the number of errors that were encountered
     */
    error_count: number;
    /**
     * 'rules' is a collection of all the rules that were applied in order
     */
    rules: {
      /**
       * 'metadata' is the metadata for the rule
       */
      metadata: {
        /**
         * Name uniquely identifies the name among all rules
         */
        name: string;
        /**
         * 'display_name' is a human-readable display name for the rule
         */
        display_name?: string;
        /**
         * 'skip' allows the creation of rules that are skipped.  Deprecated, used 'skip_expression' instead.
         */
        skip?: boolean;
        /**
         * 'skip_expression' is a template expression that is evaluated to determine if the item should be skipped.
         */
        skip_expression?: string;
        /**
         * 'skip_reason' is a human-readable reason for why the item is skipped.  This will be logged at INFO level in the report, if the item is skipped.
         */
        skip_reason?: string;
        /**
         * priority defines the order in which the rule is evaluated.  If not provided then it sorts last
         */
        priority?: number;
        /**
         * 'description' is a human-readable description of the rule
         */
        description?: string;
        /**
         * 'required_contexts' is a list of contexts that are required for the rule to run.  Deprecated, used 'skip_expression' instead.
         */
        required_contexts?: string[];
        /**
         * 'annotations' are a map of key-value pairs that are used to store additional information about the rule
         */
        annotations?: {
          [k: string]: string;
        };
        /**
         * 'classifications' are the classifications of the rule as an array of strings.
         */
        classifications?: string[];
      };
      /**
       * 'name' is the name of the rule
       */
      name: string;
      /**
       * 'skipped' is true if the rule was skipped
       */
      skipped: boolean;
      /**
       * 'skip_reason' is the reason the rule was skipped
       */
      skip_reason?: string;
      /**
       * 'findings' is the number of findings found for the rule
       */
      findings: number;
      /**
       * 'fixes' is the number of fixes applied for the rule
       */
      fixes: number;
      /**
       * 'changes' is the total number of changes applied for the rule.  In many cases a remediation requires more then one change
       */
      changes: number;
      /**
       * 'errors' is a collection of all the errors that were encountered for the rule
       */
      errors: unknown[];
      /**
       * 'error_count' is the number of errors that were encountered for the rule
       */
      error_count: number;
      /**
       * logs is a list of all log messages.
       */
      logs?: {
        time?: string;
        level?: 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR' | 'FATAL';
        message: string;
        source?: string;
        data?: {
          [k: string]: unknown;
        };
      }[];
      /**
       * logs_count is the number of log messages.
       */
      logs_count?: number;
      /**
       * 'files' is a collection of all the files that were processed for the rule
       */
      files: {
        /**
         * 'path' is the path to the file
         */
        path: string;
      }[];
      /**
       * 'file_count' is the number of files that were processed for the rule
       */
      file_count: number;
      /**
       * 'paths_with_findings' is a map of file paths to a struct indicating that the file had findings
       */
      paths_with_findings: {
        [k: string]: {};
      };
      /**
       * 'files_changed' is a map of file paths to a struct indicating that the file was changed
       */
      files_changed: {
        [k: string]: {};
      };
      /**
       * 'hooks' is a map of hook names to their details
       */
      hooks: {
        [k: string]: {
          command_path: string;
          args: string[];
          stdout: string;
          stderr: string;
          exit_code: number;
        };
      };
    }[];
    /**
     * 'hooks' is a map of hook names to their details
     */
    hooks: {
      [k: string]: {
        command_path: string;
        args: string[];
        stdout: string;
        stderr: string;
        exit_code: number;
      };
    };
  };
}
