/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Test {
  /**
   * 'type' defines the type of object
   */
  type: 'Rule' | 'Test' | 'Ruleset' | 'Context' | 'Variables' | 'Report';
  /**
   * 'version' defines the parsing of the spec
   */
  version: 'v1';
  /**
   * 'metadata' is the metadata for the object
   */
  metadata: {
    /**
     * Name uniquely identifies the name among all rules
     */
    name: string;
    /**
     * 'display_name' is a human-readable display name for the rule
     */
    display_name?: string;
    /**
     * 'skip' allows the creation of rules that are skipped.  Deprecated, used 'skip_expression' instead.
     */
    skip?: boolean;
    /**
     * 'skip_expression' is a template expression that is evaluated to determine if the item should be skipped.
     */
    skip_expression?: string;
    /**
     * 'skip_reason' is a human-readable reason for why the item is skipped.  This will be logged at INFO level in the report, if the item is skipped.
     */
    skip_reason?: string;
    /**
     * priority defines the order in which the rule is evaluated.  If not provided then it sorts last
     */
    priority?: number;
    /**
     * 'description' is a human-readable description of the rule
     */
    description?: string;
    /**
     * 'required_contexts' is a list of contexts that are required for the rule to run.  Deprecated, used 'skip_expression' instead.
     */
    required_contexts?: string[];
    /**
     * 'annotations' are a map of key-value pairs that are used to store additional information about the rule
     */
    annotations?: {
      [k: string]: string;
    };
    /**
     * 'classifications' are the classifications of the rule as an array of strings.
     */
    classifications?: string[];
  };
  /**
   * 'spec' is the specification for the test.
   */
  spec: {
    recursive_rulespace?: boolean;
    /**
     * 'rulespace' is the path to the rulespace to test.
     */
    rulespace: string;
    /**
     * 'cases' is the list of test cases to run.
     */
    cases: {
      /**
       * 'name' is the name of the test case.
       */
      name: string;
      /**
       * 'hooks_dir' is the path to the hooks directory.
       */
      hooks_dir?: string;
      /**
       * 'preset_hook' is the name of the preset hook to use.  Conflicts with 'hooks_dir'.
       */
      preset_hook?: string;
      /**
       * 'skip' is true if the test case should be skipped.  This is useful for tests that are not ready to run.  Deprecated, use 'skip_expression' instead.
       */
      skip?: boolean;
      /**
       * 'skip_expression' is a template expression that is evaluated to determine if the test case should be skipped.  This is useful for tests that are not ready to run.
       */
      skip_expression?: string;
      /**
       * 'skip_reason' is a human-readable reason for why the test case is skipped.  This will be logged at INFO level in the report, if the test case is skipped.
       */
      skip_reason?: string;
      /**
       * 'language' is the language to use for the workspace and rulespace to test.  Only files that match the language will be included int he workspace.  Only rules that match the language will be included in the rulespace.
       */
      language: string;
      /**
       * 'recursive' is true if the workspace path should be searched recursively.  This overrides the languages' default recursive behavior.
       */
      recursive?: boolean;
      /**
       * 'workspace' is the workspace to test.
       */
      workspace: {
        /**
         * 'path' is the path to load files from.  This or 'inline' is required.
         */
        path?: string;
        /**
         * 'inline' is a single file content that is loaded.  Useful if you have a lot of small files that need to be loaded and tested separated.  This or 'path' is required.
         */
        inline?: string;
        /**
         * 'mode' is the mode used for comparing 'remediated_workspace' against the remediated workspace.  Values are 'strict' (default) for a byte-level comparison of the file contents or 'ast' for a comparison of the ASTs.
         */
        mode?: 'strict' | 'ast';
      };
      /**
       * 'contexts' is the list of contexts made present to the test case.
       */
      contexts?: {
        /**
         * 'path' is the path to load files from based on 'type'.
         */
        path: string;
        /**
         * 'type' is the type of context to load.  Values are 'variables' for ORL Variable files or 'tfplan' for Terraform plan file.
         */
        type: 'variables' | 'tfplan';
      }[];
      /**
       * 'log_level' is the level of logs to capture.  Values are DEBUG, INFO, WARN, or ERROR.  Default is ERROR.
       */
      log_level?: string;
      /**
       * 'remediated_workspace' is what the remediated workspace is compared to. Any diffs = a failure.  This or 'expected_report' is required.
       */
      remediated_workspace?: {
        /**
         * 'path' is the path to load files from.  This or 'inline' is required.
         */
        path?: string;
        /**
         * 'inline' is a single file content that is loaded.  Useful if you have a lot of small files that need to be loaded and tested separated.  This or 'path' is required.
         */
        inline?: string;
        /**
         * 'mode' is the mode used for comparing 'remediated_workspace' against the remediated workspace.  Values are 'strict' (default) for a byte-level comparison of the file contents or 'ast' for a comparison of the ASTs.
         */
        mode?: 'strict' | 'ast';
      };
      /**
       * 'expected_report' is compared to the report output after remediations. Any diffs = a failure. All fields are optional - omit any field you don't want to validate.  This or 'remediated_workspace' is required.
       */
      expected_report?: {
        /**
         * 'workspace' is the path as listed in the report.
         */
        workspace?: string;
        /**
         * 'language' is the language as listed in the report.
         */
        language?: string;
        /**
         * 'version' is the version of the report that generated.
         */
        version?: string;
        /**
         * 'type' is ORL type of report generated. Should always be 'Report'.
         */
        type?: string;
        /**
         * 'findings' is the number of findings reported.
         */
        findings?: number;
        /**
         * 'fixes' is the number of fixes reported.
         */
        fixes?: number;
        /**
         * 'error_count' is the number of errors reported.
         */
        error_count?: number;
        /**
         * 'logs_count' is the number of logs messages reported.
         */
        logs_count?: number;
        /**
         * 'rules_applied' is the number of rules applied reported.
         */
        rules_applied?: number;
        /**
         * 'rules_skipped' is the number of rules skipped reported.
         */
        rules_skipped?: number;
        /**
         * 'changes' is the number of changes reported.
         */
        changes?: number;
        /**
         * 'errors' is a list of error messages reported.  The messages have to be exact matches, and in the correct order.  But they don't have to the same index as in the report (e.g. the first error here might be the third error in the report)
         */
        errors?: string[];
        /**
         * 'logs' is a list of log messages reported.  The messages have to be exact matches, and in the correct order.  But they don't have to the same index as in the report (e.g. the first log here might be the third log in the report)
         */
        logs?: {
          time?: string;
          level?: 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR' | 'FATAL';
          message: string;
          source?: string;
          data?: {
            [k: string]: unknown;
          };
        }[];
        /**
         * 'rules' is a list of rule expectations.  The rules must be in the same sequence as they appear in the actual report. Each rule is validated by position, not by name.
         */
        rules?: {
          /**
           * 'name' is the name of the rule reported.
           */
          name: string;
          /**
           * 'findings' is the number of findings reported for the rule.
           */
          findings?: number;
          /**
           * 'fixes' is the number of fixes reported for the rule.
           */
          fixes?: number;
          /**
           * 'changes' is the number of changes reported for the rule.
           */
          changes?: number;
          /**
           * 'errors' is a list of error messages reported for the rule.  The messages have to be exact matches, and in the correct order.  But they don't have to the same index as in the report (e.g. the first error here might be the third error in the report)
           */
          errors?: string[];
          /**
           * 'error_count' is the number of errors reported for the rule.
           */
          error_count?: number;
          /**
           * 'files' is a list of files reported for the rule.  The files have to be exact matches, and in the correct order.  But they don't have to the same index as in the report (e.g. the first file here might be the third file in the report)
           */
          files?: string[];
          /**
           * 'file_count' is the number of files reported for the rule.
           */
          file_count?: number;
          /**
           * 'hooks' is a map of hook names to their details.  The hooks must be in the same sequence as they appear in the actual report. Each hook is validated by position, not by name.
           */
          hooks?: {
            [k: string]: {
              command_path: string;
              args: string[];
              stdout: string;
              stderr: string;
              exit_code: number;
            };
          };
          /**
           * 'logs' is a list of log messages reported for the rule.  The messages have to be exact matches, and in the correct order.  But they don't have to the same index as in the report (e.g. the first log here might be the third log in the report)
           */
          logs?: {
            time?: string;
            level?: 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR' | 'FATAL';
            message: string;
            source?: string;
            data?: {
              [k: string]: unknown;
            };
          }[];
          /**
           * 'logs_count' is the number of log messages reported for the rule.
           */
          logs_count?: number;
        }[];
        /**
         * 'hooks' is a map of hook names to their details.  The hooks must be in the same sequence as they appear in the actual report. Each hook is validated by position, not by name.
         */
        hooks?: {
          [k: string]: {
            command_path: string;
            args: string[];
            stdout: string;
            stderr: string;
            exit_code: number;
          };
        };
        /**
         * 'output_file' is the path to the file that was output.  This is used to validate the file output.
         */
        output_file?: string;
      };
    }[];
  };
}
