/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Variables is an ORL object that contains key value pairs.
 */
export interface Variables {
  /**
   * 'type' defines the type of object
   */
  type: 'Rule' | 'Test' | 'Ruleset' | 'Context' | 'Variables' | 'Report';
  /**
   * 'version' defines the parsing of the spec
   */
  version: 'v1';
  /**
   * 'metadata' is the metadata for the object
   */
  metadata: {
    /**
     * Name uniquely identifies the name among all rules
     */
    name: string;
    /**
     * 'display_name' is a human-readable display name for the rule
     */
    display_name?: string;
    /**
     * 'skip' allows the creation of rules that are skipped.  Deprecated, used 'skip_expression' instead.
     */
    skip?: boolean;
    /**
     * 'skip_expression' is a template expression that is evaluated to determine if the item should be skipped.
     */
    skip_expression?: string;
    /**
     * 'skip_reason' is a human-readable reason for why the item is skipped.  This will be logged at INFO level in the report, if the item is skipped.
     */
    skip_reason?: string;
    /**
     * priority defines the order in which the rule is evaluated.  If not provided then it sorts last
     */
    priority?: number;
    /**
     * 'description' is a human-readable description of the rule
     */
    description?: string;
    /**
     * 'required_contexts' is a list of contexts that are required for the rule to run.  Deprecated, used 'skip_expression' instead.
     */
    required_contexts?: string[];
    /**
     * 'annotations' are a map of key-value pairs that are used to store additional information about the rule
     */
    annotations?: {
      [k: string]: string;
    };
    /**
     * 'classifications' are the classifications of the rule as an array of strings.
     */
    classifications?: string[];
  };
  data: {
    [k: string]: string;
  };
}
